#!/usr/bin/env bash

set -e

require() {
  if [[ -z `command -v $1` ]]; then
    echo "Please install $1"
    exit 1
  fi
}

URL=https://www.bitmex.com/api/explorer/swagger.json
MODEL=net.ninety.bitmex.model
API=net.ninety.bitmex.api

gen() {
  curl -XPOST "https://generator.swagger.io/api/gen/clients/java"\
       -H "accept: application/json"\
       -H "Content-Type: application/json"\
       -d "{\"spec\":{},\"options\":{\"modelPackage\":\"$MODEL\",\"apiPackage\":\"$API\"},\"swaggerUrl\":\"$URL\"}"
}

# check
require curl
require jq

# cleanup
rm -rf java-client output.zip target

# download
curl -o output.zip `gen | jq .link | tr -d '"'`

# extract
unzip output.zip

# create target folder
mkdir target
mv java-client/src target
rm -rf target/src/main/java/net/ninety/bitmex/auth
rm -rf target/src/main/java/net/ninety/bitmex/api
rm -rf target/src/test/java/net/ninety/bitmex/api
rm target/src/main/java/net/ninety/bitmex/*.java
cp build.gradle target
cp release target
cp module-info.java target/src/main/java

